"""empty message

Revision ID: 51dfbf1ec1ce
Revises: b99444cdef90
Create Date: 2019-06-23 05:15:48.372961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "51dfbf1ec1ce"
down_revision = "b99444cdef90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question_categories",
        sa.Column("description", sa.String(length=80), nullable=True),
    )
    op.add_column("question_categories", sa.Column("image", sa.String(), nullable=True))
    op.add_column("questions", sa.Column("closed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "closed")
    op.drop_column("question_categories", "image")
    op.drop_column("question_categories", "description")
    # ### end Alembic commands ###
